name: alexcnc
description: Smart CNC Pro - Android client for ESP32 / modified-Grbl CNC machines.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.6
  material_symbols_icons: ^4.2960.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
