name: native_vlc_player
description: Native libVLC based RTSP player for AlexCNC (directly embeds VLCVideoLayout).
version: 0.1.0
homepage:
publish_to: 'none'

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.alexcnc.native_vlc_player
        pluginClass: NativeVlcPlayerPlugin
